[구글 코랩(Colab)에서 실행하기](https://colab.research.google.com/github/lovedlim/bigdata_analyst_cert_v2/blob/main/part4/ch4/p4_type1.ipynb)

## 작업형1

### 문제1

제공된 데이터셋(df)의 age(나이) 컬럼을 활용하여 제3사분위수(75% 백분위수)와 제1사분위수(25% 백분위수)의 차이(IQR: 사분위간 범위)를 구하시오. 계산된 결과의 소수점 이하를 버리고 정수 형태로 제출하시오.

In [5]:
import pandas as pd
# df = pd.read_csv("data4-1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch4/data4-1.csv")
df.head()

     id   age city    f1  f2   f3    f4         f5
0  id01   2.0   서울   NaN   0  NaN  ENFJ  91.297791
1  id02   9.0   서울  70.0   1  NaN  ENFJ  60.339826
2  id03  27.0   서울  61.0   1  NaN  ISTJ  17.252986
3  id04  75.0   서울   NaN   2  NaN  INFP  52.667078
4  id05  24.0   서울  85.0   2  NaN  ISFJ  29.269869

In [6]:
Q3 = df['age'].quantile(0.75)
Q1 = df['age'].quantile(0.25)
print((Q3- Q1).astype(int))

50

In [ ]:
import pandas as pd
# df = pd.read_csv("data4-1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch4/data4-1.csv")

# 1) 3사분위수와 1사분위수의 차이를 절대값으로 계산
q1 = df['age'].quantile(0.25)
q3 = df['age'].quantile(0.75)
result = abs(q1 - q3)

# 2) 소수점 이하를 버리고, 정수로 출력
print(int(result))

50

### 문제2

제공된 데이터셋(df)에서 아래 3가지 조건을 모두 만족하는 데이터(행)의 총 개수를 구하시오.

(loves + wows) / reactions의 비율이 40% 초과

(loves + wows) / reactions의 비율이 50% 미만

type 컬럼의 값이 'video'인 데이터

In [7]:
import pandas as pd
# df = pd.read_csv("data4-2.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch4/data4-2.csv")
df

,id,type,reactions,comments,shares,likes,loves,wows,hahas,sads,angrys
0,1,video,529,512,262,432,92,3,1,1,0
1,2,photo,150,0,0,150,0,0,0,0,0
2,3,video,227,236,57,204,21,1,1,0,0
3,4,photo,111,0,0,111,0,0,0,0,0
4,5,photo,213,0,0,204,9,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
7045,7046,photo,89,0,0,89,0,0,0,0,0
7046,7047,photo,16,0,0,14,1,0,1,0,0
7047,7048,photo,2,0,0,1,1,0,0,0,0
7048,7049,photo,351,12,22,349,2,0,0,0,0
7049,7050,photo,17,0,0,17,0,0,0,0,0

In [12]:
df['ratio'] = (df['loves'] + df['wows'])/df['reactions']
cond1 = df['ratio'] > 0.4
cond2 = df['ratio'] < 0.5
cond3 = df['type'] == 'video'

print(len(df[cond1 & cond2 & cond3]))

90

In [ ]:
import pandas as pd
# df = pd.read_csv("data4-2.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch4/data4-2.csv")

# 1) 비율이 40%보다 크고 50%보다 작은 조건
cond1 = (df['loves'] + df['wows']) / df['reactions'] > 0.4
cond2 = (df['loves'] + df['wows']) / df['reactions'] < 0.5

# 2) type이 video인 조건
cond3 = df['type'] == 'video'

# 3) 조건에 맞는 데이터 수 구하기
print(len(df[cond1 & cond2 & cond3]))

90

### 문제3

제공된 데이터셋(df)을 활용하여 아래 3가지 조건을 모두 만족하는 데이터(행)의 총 개수를 구하시오.

country(국가) 컬럼의 값이 "United Kingdom"

date_added(등록일)의 연도가 2018년

date_added(등록일)의 월이 1월

In [19]:
df['date_added'] = pd.to_datetime(df['date_added'])
df['year'] = df['date_added'].dt.year
df['month'] = df['date_added'].dt.month
#df.info()

cond1 = df['country'] == "United Kingdom"
cond2 = (df['year'] == 2018) & (df['month'] == 1)

print(df)
print(len(df[cond1 & cond2]))

     show_id     type                  title         director  \
0         s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1         s2  TV Show          Blood & Water              NaN
2         s3  TV Show              Ganglands  Julien Leclercq
3         s4  TV Show  Jailbirds New Orleans              NaN
4         s5  TV Show           Kota Factory              NaN
...      ...      ...                    ...              ...
8802   s8803    Movie                 Zodiac    David Fincher
8803   s8804  TV Show            Zombie Dumb              NaN
8804   s8805    Movie             Zombieland  Ruben Fleischer
8805   s8806    Movie                   Zoom     Peter Hewitt
8806   s8807    Movie                 Zubaan      Mozez Singh

                                                   cast        country  \
0                                                   NaN  United States
1     Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2     Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                   NaN            NaN
4     Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India
...                                                 ...            ...
8802  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...  United States
8803                                                NaN            NaN
8804  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...  United States
8805  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...  United States
8806  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...          India

     date_added  release_year rating   duration  \
0    2021-09-25          2020  PG-13     90 min
1    2021-09-24          2021  TV-MA  2 Seasons
2    2021-09-24          2021  TV-MA   1 Season
3    2021-09-24          2021  TV-MA   1 Season
4    2021-09-24          2021  TV-MA  2 Seasons
...         ...           ...    ...        ...
8802 2019-11-20          2007      R    158 min
8803 2019-07-01          2018  TV-Y7  2 Seasons
8804 2019-11-01          2009      R     88 min
8805 2020-01-11          2006     PG     88 min
8806 2019-03-02          2015  TV-14    111 min

                                              listed_in    year  month
0                                         Documentaries  2021.0    9.0
1       International TV Shows, TV Dramas, TV Mysteries  2021.0    9.0
2     Crime TV Shows, International TV Shows, TV Act...  2021.0    9.0
3                                Docuseries, Reality TV  2021.0    9.0
4     International TV Shows, Romantic TV Shows, TV ...  2021.0    9.0
...                                                 ...     ...    ...
8802                     Cult Movies, Dramas, Thrillers  2019.0   11.0
8803             Kids' TV, Korean TV Shows, TV Comedies  2019.0    7.0
8804                            Comedies, Horror Movies  2019.0   11.0
8805                 Children & Family Movies, Comedies  2020.0    1.0
8806     Dramas, International Movies, Music & Musicals  2019.0    3.0

[8807 rows x 13 columns]
6

In [13]:
import pandas as pd
# df = pd.read_csv("data4-3.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch4/data4-3.csv")
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries"
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV"
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ..."
...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers"
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies"
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies"
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies"
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals"

In [ ]:
# 방법1
import pandas as pd
# df = pd.read_csv("data4-3.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch4/data4-3.csv")

# 1) datetime으로 형변환
df['date_added'] = pd.to_datetime(df['date_added'])

# 2) dt를 활용해 year과 month 파생변수 생성
df['year'] = df['date_added'].dt.year
df['month'] = df['date_added'].dt.month

# 3) 조건
cond1 = df['country'] == "United Kingdom"
cond2 = df['year'] == 2018
cond3 = df['month'] == 1

# 4) 조건에 맞는 데이터 수 출력
print(len(df[cond1 & cond2 & cond3]))

6

In [ ]:
# 방법2
# df = pd.read_csv("data4-3.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch4/data4-3.csv")

# 1) datetime으로 형변환
df['date_added'] = pd.to_datetime(df['date_added'])

# 2) 조건
cond1 = df['country'] == "United Kingdom"
cond2 = df['date_added'] >= '2018-1-1'
cond3 = df['date_added'] <= '2018-1-31'

# 3) 조건에 맞는 데이터 수 출력
print(len(df[cond1 & cond2 & cond3]))

6