[구글 코랩(Colab)에서 실행하기](https://colab.research.google.com/github/lovedlim/bigdata_analyst_cert_v2/blob/main/part4/ch9/p9_type3.ipynb)

## 작업형3

### 문제1-1

데이터를 분할하고 회귀 모델을 구축한 뒤 유의한 변수의 개수를 구하시오

데이터를 id <= 140은 train, id > 140은 test 데이터로 분할하시오. train 데이터를 사용하여 design을 종속변수로, c1~c5를 독립변수로 하는 다중선형회귀분석을 수행하고, 상수항을 제외한 독립변수 중 유의수준 0.05 미만인 유의한 변수의 개수를 구하시오.

In [2]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert_v2/main/part4/ch9/design.csv")
df

      id     design        c1        c2        c3        c4        c5
0      1  58.962471  0.374540  0.642032  0.103124  0.168935  0.707239
1      2  42.006534  0.950714  0.084140  0.902553  0.278590  0.152539
2      3  55.831980  0.731994  0.161629  0.505252  0.177010  0.576288
3      4  64.458592  0.598658  0.898554  0.826457  0.088703  0.606715
4      5  61.342792  0.156019  0.606429  0.320050  0.120636  0.424131
..   ...        ...       ...       ...       ...       ...       ...
195  196  49.976045  0.349210  0.930757  0.473962  0.872124  0.091582
196  197  61.148418  0.725956  0.858413  0.667558  0.932118  0.917314
197  198  38.647434  0.897110  0.428994  0.172320  0.565133  0.136819
198  199  49.458373  0.887086  0.750871  0.192289  0.696651  0.950237
199  200  69.747684  0.779876  0.754543  0.040869  0.922499  0.446006

[200 rows x 7 columns]

In [3]:
train = df[df['id'] <= 140]
print(train)
test = df[df['id'] > 140]

      id     design        c1        c2        c3        c4        c5
0      1  58.962471  0.374540  0.642032  0.103124  0.168935  0.707239
1      2  42.006534  0.950714  0.084140  0.902553  0.278590  0.152539
2      3  55.831980  0.731994  0.161629  0.505252  0.177010  0.576288
3      4  64.458592  0.598658  0.898554  0.826457  0.088703  0.606715
4      5  61.342792  0.156019  0.606429  0.320050  0.120636  0.424131
..   ...        ...       ...       ...       ...       ...       ...
135  136  58.457931  0.323203  0.040729  0.944766  0.877201  0.272307
136  137  66.020866  0.518791  0.855461  0.849647  0.392445  0.018391
137  138  63.945956  0.703019  0.703658  0.247348  0.816599  0.914299
138  139  54.083051  0.363630  0.474174  0.450544  0.439135  0.117751
139  140  55.031334  0.971782  0.097834  0.129159  0.376944  0.576516

[140 rows x 7 columns]

In [4]:
import statsmodels.formula.api as smf
formula = "design ~ c1 + c2 + c3 + c4 + c5"
model = smf.ols(formula, data = train).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 design   R-squared:                       0.266
Model:                            OLS   Adj. R-squared:                  0.238
Method:                 Least Squares   F-statistic:                     9.697
Date:                Tue, 16 Jun 2026   Prob (F-statistic):           6.37e-08
Time:                        12:09:50   Log-Likelihood:                -468.72
No. Observations:                 140   AIC:                             949.4
Df Residuals:                     134   BIC:                             967.1
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     53.0220      2.294     23.112      0.000      48.485      57.559
c1            -4.9403      2.008     -2.460      0.015      -8.912      -0.969
c2            11.3795      2.045      5.564      0.000       7.335      15.424
c3             2.6960      1.920      1.404      0.163      -1.101       6.493
c4             5.7978      2.176      2.664      0.009       1.494      10.102
c5            -1.5018      2.067     -0.726      0.469      -5.590       2.587
==============================================================================
Omnibus:                        3.969   Durbin-Watson:                   2.052
Prob(Omnibus):                  0.137   Jarque-Bera (JB):                3.019
Skew:                           0.227   Prob(JB):                        0.221
Kurtosis:                       2.441   Cond. No.                         7.68
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [5]:
print((model.pvalues[1:] < 0.05).sum())

3

In [1]:
import pandas as pd
df = pd.read_csv("design.csv")
# df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert_v2/main/part4/ch9/design.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'design.csv'

In [12]:
from statsmodels.formula.api import ols

# 1) train, test 데이터 분리
cond1 = df['id'] <= 140
cond2 = df['id'] > 140
train = df[cond1].copy()
test = df[cond2].copy()

# 2) 전체 변수 사용 회귀분석
model = ols("design ~ c1 + c2 + c3 + c4 + c5", data=train).fit()
print(model.summary())

# 3) 상수항(Intercept)은 제외하고, p-value가 0.05보다 작은 독립변수의 개수를 계산
print(model.pvalues[1:] < 0.05)
sum(model.pvalues[1:] < 0.05)

                            OLS Regression Results
==============================================================================
Dep. Variable:                 design   R-squared:                       0.266
Model:                            OLS   Adj. R-squared:                  0.238
Method:                 Least Squares   F-statistic:                     9.697
Date:                Tue, 16 Jun 2026   Prob (F-statistic):           6.37e-08
Time:                        10:14:02   Log-Likelihood:                -468.72
No. Observations:                 140   AIC:                             949.4
Df Residuals:                     134   BIC:                             967.1
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     53.0220      2.294     23.112      0.000      48.485      57.559
c1            -4.9403      2.008     -2.460      0.015      -8.912      -0.969
c2            11.3795      2.045      5.564      0.000       7.335      15.424
c3             2.6960      1.920      1.404      0.163      -1.101       6.493
c4             5.7978      2.176      2.664      0.009       1.494      10.102
c5            -1.5018      2.067     -0.726      0.469      -5.590       2.587
==============================================================================
Omnibus:                        3.969   Durbin-Watson:                   2.052
Prob(Omnibus):                  0.137   Jarque-Bera (JB):                3.019
Skew:                           0.227   Prob(JB):                        0.221
Kurtosis:                       2.441   Cond. No.                         7.68
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
c1     True
c2     True
c3    False
c4     True
c5    False
dtype: bool

3

### 문제1-2

[문제 1]에서 선택된 유의한 독립변수들(c1, c2, c4)만 사용하여 train 데이터로 회귀 모델을 재학습시키시오. 이 모델을 통해 얻은 train 데이터의 design 예측값과 실제 design 값 간의 피어슨 상관계수를 구하시오.

출력 형식: 소수점 셋째 자리까지 반올림 (예: 0.785)

In [6]:
formula2 = "design ~ c1+ c2+ c4"
model = smf.ols(formula2, data = train).fit()
pred = model.predict(train)
print(pred)

0      60.071154
1      51.703419
2      53.004302
3      61.348118
4      60.437781
         ...
135    58.005677
136    63.147029
137    63.191802
138    59.929248
139    52.366341
Length: 140, dtype: float64

In [17]:
df_design = pd.DataFrame({'train' : train['design'], 'pred': pred})
df_design

         train       pred
0    58.962471  60.071154
1    42.006534  51.703419
2    55.831980  53.004302
3    64.458592  61.348118
4    61.342792  60.437781
..         ...        ...
135  58.457931  58.005677
136  66.020866  63.147029
137  63.945956  63.191802
138  54.083051  59.929248
139  55.031334  52.366341

[140 rows x 2 columns]

In [7]:
#df_design.corr().loc['train', 'pred']

round(train['design'].corr(pred),3) # 피어슨이 default
print(round(train['design'].corr(pred),3))

0.501

In [ ]:
# 방법1
# 1) 유의한 변수만 사용한 회귀 분석
model = ols("design ~ c1 + c2 + c4", data=train).fit()

# 2) train 데이터에서 design의 예측
train['pred_design'] = model.predict(train)

# 3) 피어슨 상관계수 계산
result = train['design'].corr(train['pred_design'])
round(result,3)

0.501

In [ ]:
# 방법2(추가tip)
from scipy.stats import pearsonr
# 1) 유의한 변수만 사용한 회귀 분석
model = ols("design ~ c1 + c2 + c4", data=train).fit()

# 학습데이터에서 예측값 계산
train['pred_design'] = model.predict(train)

# 예측값과 실제 design 값 사이의 피어슨 상관계수 계산
c, p = pearsonr(train['design'], train['pred_design'])
round(c,3)

0.501

### 문제1-3

[문제 2]에서 학습시킨 재구축 모델을 test 데이터에 적용하여 예측값을 산출하고, 실제 design 값과의 RMSE(평균제곱근오차)를 구하시오.

출력 형식: 소수점 셋째 자리까지 반올림 (예: 12.345)

In [8]:
test

      id     design        c1        c2        c3        c4        c5
140  141  66.574168  0.962447  0.491616  0.954051  0.462680  0.274055
141  142  48.521635  0.251782  0.473472  0.606175  0.301378  0.554178
142  143  57.754669  0.497249  0.173202  0.228643  0.747609  0.651420
143  144  52.072094  0.300878  0.433852  0.671701  0.502720  0.829742
144  145  65.085687  0.284840  0.398505  0.618128  0.232213  0.206421
145  146  49.939884  0.036887  0.615850  0.358163  0.899575  0.010996
146  147  54.425912  0.609564  0.635094  0.113558  0.383891  0.136886
147  148  57.076121  0.502679  0.045304  0.671573  0.543553  0.900019
148  149  72.282948  0.051479  0.374613  0.520308  0.906472  0.873890
149  150  59.873168  0.278646  0.625860  0.772318  0.624238  0.597413
150  151  51.365151  0.908266  0.503136  0.520164  0.116898  0.600517
151  152  79.848061  0.239562  0.856490  0.852182  0.939832  0.665037
152  153  49.166413  0.144895  0.658694  0.551907  0.627708  0.175371
153  154  36.260326  0.489453  0.162934  0.560938  0.334906  0.914412
154  155  55.149595  0.985650  0.070569  0.876654  0.139272  0.418771
155  156  57.674528  0.242055  0.642419  0.403483  0.794025  0.383139
156  157  46.208193  0.672136  0.026511  0.134015  0.620073  0.518918
157  158  65.063055  0.761620  0.585776  0.028783  0.533461  0.046966
158  159  67.281898  0.237638  0.940230  0.755137  0.893893  0.166283
159  160  56.472878  0.728216  0.575474  0.620310  0.788597  0.738034
160  161  44.645324  0.367783  0.388170  0.704080  0.151675  0.082799
161  162  65.480193  0.632306  0.643288  0.212964  0.311722  0.603152
162  163  61.432367  0.633530  0.458253  0.136371  0.248489  0.245349
163  164  59.597357  0.535775  0.545617  0.014545  0.743946  0.389296
164  165  74.410165  0.090290  0.941465  0.350588  0.033532  0.288694
165  166  49.080427  0.835302  0.386103  0.589918  0.569890  0.355673
166  167  52.465093  0.320780  0.961191  0.392244  0.762459  0.719046
167  168  59.333828  0.186519  0.905351  0.437475  0.876766  0.297122
168  169  53.862251  0.040775  0.195791  0.904159  0.342082  0.566405
169  170  58.087728  0.590893  0.069361  0.348255  0.821257  0.476050
170  171  49.811712  0.677564  0.100778  0.513989  0.110632  0.663671
171  172  58.613179  0.016588  0.018222  0.783653  0.846452  0.936830
172  173  41.777747  0.512093  0.094443  0.396543  0.127489  0.732572
173  174  71.015391  0.226496  0.683007  0.622087  0.397287  0.214940
174  175  55.343137  0.645173  0.071189  0.862364  0.797295  0.031183
175  176  63.122525  0.174366  0.318976  0.949521  0.149917  0.262264
176  177  62.711180  0.690938  0.844875  0.147073  0.229251  0.595078
177  178  58.677446  0.386735  0.023272  0.926588  0.722253  0.051426
178  179  67.478825  0.936730  0.814468  0.492116  0.720037  0.496366
179  180  60.652948  0.137521  0.281855  0.258244  0.641148  0.596843
180  181  60.926390  0.341066  0.118165  0.459136  0.693948  0.334244
181  182  71.200483  0.113474  0.696737  0.980033  0.542724  0.770912
182  183  59.531781  0.924694  0.628943  0.492618  0.251799  0.106598
183  184  66.739752  0.877339  0.877472  0.328752  0.345696  0.075138
184  185  57.837363  0.257942  0.735071  0.633401  0.181598  0.728189
185  186  75.581500  0.659984  0.803481  0.240146  0.908451  0.495491
186  187  51.278845  0.817222  0.282035  0.075863  0.583392  0.688402
187  188  68.840766  0.555201  0.177440  0.128880  0.400851  0.434827
188  189  60.249368  0.529651  0.750615  0.128046  0.462006  0.246402
189  190  52.905477  0.241852  0.806835  0.151903  0.947283  0.819102
190  191  61.947067  0.093103  0.990505  0.138827  0.153351  0.799416
191  192  52.566226  0.897216  0.412618  0.640875  0.586230  0.694696
192  193  63.800889  0.900418  0.372018  0.181880  0.505889  0.272145
193  194  56.598914  0.633101  0.776413  0.345667  0.611454  0.590231
194  195  49.958693  0.339030  0.340804  0.896788  0.018110  0.360974
195  196  49.976045  0.349210  0.930757  0.473962  0.872124  0.091582
196  197  61.148418  0.725956  0.858413  0.667558  0.932118  0.917314
197  198  38.647434  0.897110  0.428994  0.172320  0.565133  0.136819
198  199  49.458373  0.887086  0.750871  0.192289  0.696651  0.950237
199  200  69.747684  0.779876  0.754543  0.040869  0.922499  0.446006

In [12]:
prediction = model.predict(test)

import numpy as np
from sklearn.metrics import mean_squared_error
def rmse(y, y_pred):
  return np.sqrt(mean_squared_error(y,y_pred))

print(rmse(test['design'], prediction))

8.488336110545161

In [ ]:
# 1) test데이터에서 design값 계산
test['pred_design'] = model.predict(test)

# 2) test데이터에 대한 RMSE 계산
from sklearn.metrics import root_mean_squared_error
rmse = root_mean_squared_error(test['design'], test['pred_design'])
round(rmse, 3)

8.488

### 문제2-1

제공된 데이터를 바탕으로 Churn을 종속변수로 하고, MonthlyCharges, CustomerTenure, HasPhoneService, HasTechInsurance를 독립변수로 설정하여 로지스틱 회귀분석을 수행하시오. 분석 결과 중 MonthlyCharges 변수의 p-value(유의확률)를 구하시오.

출력 형식: 소수점 셋째 자리까지 반올림 (예: 0.012)

In [16]:
import statsmodels.formula.api as smf
formula = "Churn ~ MonthlyCharges + CustomerTenure + HasPhoneService + HasTechInsurance"
model = smf.logit(formula, data = df).fit()

print(model.summary())
print(model.pvalues['MonthlyCharges'])

Optimization terminated successfully.
         Current function value: 0.582234
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                  Churn   No. Observations:                   80
Model:                          Logit   Df Residuals:                       75
Method:                           MLE   Df Model:                            4
Date:                Tue, 16 Jun 2026   Pseudo R-squ.:                  0.1585
Time:                        12:46:26   Log-Likelihood:                -46.579
converged:                       True   LL-Null:                       -55.352
Covariance Type:            nonrobust   LLR p-value:                  0.001513
====================================================================================
                       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept           -4.4731      1.437     -3.114      0.002      -7.289      -1.657
MonthlyCharges       0.0503      0.019      2.640      0.008       0.013       0.088
CustomerTenure       0.0428      0.014      3.016      0.003       0.015       0.071
HasPhoneService     -0.3558      0.525     -0.677      0.498      -1.386       0.674
HasTechInsurance    -0.4868      0.518     -0.940      0.347      -1.502       0.529
====================================================================================
0.008293105744239599

In [13]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert_v2/main/part4/ch9/retention.csv")
df.head()

,CustomerID,MonthlyCharges,CustomerTenure,HasPhoneService,HasTechInsurance,Churn
0,1,77.450712,47,1,1,1
1,2,67.926035,68,1,1,0
2,3,79.715328,45,0,1,1
3,4,92.845448,2,1,0,1
4,5,66.487699,27,1,1,0

In [ ]:
import pandas as pd
df = pd.read_csv("retention.csv")
# df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert_v2/main/part4/ch9/retention.csv")
df.head()

,CustomerID,MonthlyCharges,CustomerTenure,HasPhoneService,HasTechInsurance,Churn
0,1,77.450712,47,1,1,1
1,2,67.926035,68,1,1,0
2,3,79.715328,45,0,1,1
3,4,92.845448,2,1,0,1
4,5,66.487699,27,1,1,0

In [ ]:
import pandas as pd
from statsmodels.formula.api import logit

# 1) 로지스틱 회귀분석 수행
formula = 'Churn ~ MonthlyCharges + CustomerTenure + HasPhoneService + HasTechInsurance'
model = logit(formula, data=df).fit()

# 2) 학습된 모델의 회귀 분석 결과 출력
print(model.summary())

# 3) 'MonthlyCharges' 변수의 p-value 확인
round(model.pvalues['MonthlyCharges'], 3)

Optimization terminated successfully.
         Current function value: 0.582234
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                  Churn   No. Observations:                   80
Model:                          Logit   Df Residuals:                       75
Method:                           MLE   Df Model:                            4
Date:                Mon, 03 Mar 2025   Pseudo R-squ.:                  0.1585
Time:                        12:06:06   Log-Likelihood:                -46.579
converged:                       True   LL-Null:                       -55.352
Covariance Type:            nonrobust   LLR p-value:                  0.001513
====================================================================================
                       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept           -4.4731      1.437     -3.114      0.002      -7.289      -1.657
MonthlyCharges       0.0503      0.019      2.640      0.008       0.013       0.088
CustomerTenure       0.0428      0.014      3.016      0.003       0.015       0.071
HasPhoneService     -0.3558      0.525     -0.677      0.498      -1.386       0.674
HasTechInsurance    -0.4868      0.518     -0.940      0.347      -1.502       0.529
====================================================================================

0.008

### 문제2-2

[문제 1]에서 학습된 로지스틱 회귀 모델을 바탕으로, 다른 조건이 일정할 때 HasPhoneService(전화 서비스 이용 여부) 변수가 1단위 증가할 때의 오즈비(Odds Ratio, 승산비)를 구하시오.

출력 형식: 소수점 셋째 자리까지 반올림 (예: 1.456)

In [18]:
import numpy as np
print(round(np.exp(model.params['HasPhoneService']),3))

0.701

In [ ]:
# 1) 오즈비 계산
import numpy as np
result = np.exp(model.params['HasPhoneService'])
round(result, 3)

0.701

### 문제2-3

[문제 1]에서 학습된 모델을 사용하여 전체 데이터(df)의 고객별 이탈 확률을 예측하시오. 예측된 이탈 확률이 0.3을 초과하는 고객의 총 수(건수)를 구하시오.

출력 형식: 정수 형태 (예: 45)

In [24]:
pred = model.predict(df)
print(pred)
print((pred> 0.3).sum())

0     0.643397
1     0.733174
2     0.725944
3     0.480867
4     0.306304
        ...
75    0.516097
76    0.810504
77    0.355781
78    0.556763
79    0.166611
Length: 80, dtype: float64
65

In [ ]:
# 1) 각 고객의 이탈 확률을 예측
pred_probs = model.predict(df)

# 2) 예측한 이탈 확률이 0.3 초과하는 고객의 수
sum(pred_probs > 0.3)

65