[구글 코랩(Colab)에서 실행하기](https://colab.research.google.com/github/lovedlim/bae-v3/blob/main/part4/ch10/p10_type1.ipynb)

## 작업형1

### 문제1: 3번째로 높은 정답률을 소수 3째자리까지 나타내시오

In [2]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bae-v3/main/part4/ch10/subject_performance.csv")

df.head()

        major_topic             sub_topic  student_id  is_correct
0       Mathematics  Discrete Mathematics         359           1
1       Mathematics  Discrete Mathematics         621           1
2  Computer Science             Databases        1366           1
3       Mathematics  Discrete Mathematics        1377           0
4           Physics             Mechanics         535           0

In [12]:
(df.groupby('major_topic')['is_correct'].sum())/df.groupby('major_topic')['is_correct'].count()

major_topic
Computer Science    0.695067
Mathematics         0.701099
Physics             0.672854
Name: is_correct, dtype: float64

In [18]:
acc = df.groupby('major_topic')['is_correct'].mean()
print(acc)

major_topic
Computer Science    0.695067
Mathematics         0.701099
Physics             0.672854
Name: is_correct, dtype: float64

1-2. 1-1.테이블에서 내림차순 정렬 후 중복제거

In [25]:
result = acc.sort_values(ascending = False).drop_duplicates()
print(round(result,3))

major_topic
Mathematics         0.701
Computer Science    0.695
Physics             0.673
Name: is_correct, dtype: float64

In [ ]:
# 풀이1

# 1. 소주제별 정답률 계산 (정답1, 오답0)
acc = df.groupby("sub_topic")["is_correct"].mean()

# 2. 내림차순 정렬 후 중복 제거
result = acc.sort_values(ascending=False).drop_duplicates()

print(round(result, 3))
#정답: 0.674

sub_topic
Algorithms              0.787
Mechanics               0.694
Calculus                0.674
Quantum                 0.668
Electromagnetism        0.659
Discrete Mathematics    0.644
Databases               0.641
Name: is_correct, dtype: float64

In [ ]:
# 풀이2
# 1. 소주제별 정답률 계산 (정답1, 오답0)
acc = df.groupby("sub_topic")["is_correct"].mean()

# 2. 상위 4개 추출 후 중복 제거
result = acc.nlargest(4).drop_duplicates()

print(round(result, 3))
#정답: 0.674

sub_topic
Algorithms    0.787
Mechanics     0.694
Calculus      0.674
Name: is_correct, dtype: float64

In [ ]:
# 3번째로 높은 정답률 출력
print(round(result.iloc[2],3))

0.674

### 문제2 : 25년 7월의 price 합계

In [26]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bae-v3/main/part4/ch10/cafe_sales.csv")
df.head()

         order_date  category      item  price
0  2025.03.08 23:30       tea  GreenTea   6861
1  2025.10.01 13:05    coffee     Latte   6080
2  2025.04.30 17:32  smoothie     Mango   6116
3  2025.12.07 06:45       tea  BlackTea   7807
4  2024.04.10 00:40   dessert    Cookie   7964

In [32]:
df['order_date'] = pd.to_datetime(df['order_date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_date  1000 non-null   datetime64[ns]
 1   category    1000 non-null   object
 2   item        1000 non-null   object
 3   price       1000 non-null   int64
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 31.4+ KB

In [33]:
df['year'] = df['order_date'].dt.year
df['month'] = df['order_date'].dt.month
df['day'] = df['order_date'].dt.day

In [38]:
cond = (df['year'] == 2025) & (df['month'] == 7)
df[cond]['price'].sum()

np.int64(328741)

In [ ]:
# 2-1
# 1. order_date → 연-월 변환
df["order_date"] = pd.to_datetime(df["order_date"])
df["year_month"] = df["order_date"].dt.to_period("M")
df.head()

# 2. 연-월 단위로 그룹화하여 각 월의 총 매출액(price 합계)을 계산
monthly_sales = df.groupby("year_month")["price"].sum()

# 3. 연-월별 총매출액 중 상위 2개만 추출
print(monthly_sales.nlargest(3))

# 정답: 328741

year_month
2025-03    347848
2025-07    328741
2025-05    311810
Freq: M, Name: price, dtype: int64

In [ ]:
# 2-2

# 1. 연-월별 총매출액 중 상위 4개만 추출
top4 = monthly_sales.nlargest(4)
target_ym = top4.index[3]

# 2. 4번째로 큰 연-월에 해당하는 데이터만 추출
cond = df["year_month"] == target_ym
df = df[cond]

# 3. 해당 연-월의 카테고리별 매출 합계 중 최댓값 계산
cate = df.groupby("category")["price"].sum()

print(cate.max())

# 정답: 104660

104660

### 문제3

제공된 hamspam.csv 데이터셋은 메시지 내용(text)과 해당 메시지가 스팸인지 정상인지 분류한 라벨(label)로 이루어져 있다.

각 메시지 내용을 공백(띄어쓰기)을 기준으로 분리했을 때의 단어 개수를 구하시오.
그 후, 스팸 메시지(spam)의 평균 단어 수와 정상 메시지(ham)의 평균 단어 수의 차이의 절댓값을 계산하고, 이를 소수점 셋째 자리까지 반올림하여 구하시오.

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bae-v3/main/part4/ch10/hamspam.csv")
df.head()

  label                                               text
0   ham  Incididunt tempor elit sit do aliqua eiusmod a...
1   ham       Adipiscing tempor lorem ipsum dolore tempor.
2  spam    Tempor tempor magna sed incididunt consectetur.
3   ham  Consectetur incididunt amet adipiscing amet lo...
4   ham                  Sit ipsum labore sit do sit elit.

In [ ]:
# 풀이1
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bae-v3/main/part4/ch10/hamspam.csv")

# 1. 각 메시지의 단어 개수 구하기 (띄어쓰기 기준)
df["단어"] = df["text"].str.split()
df["단어수"] = df["단어"].str.len()
df.head()

# 체크 (2번째 행)
# print(df["text"][1])
# print(df["단어"][1])
# print(df["단어수"][1])

# 2. 스팸과 정상 메시지의 평균 단어 수 구하기
m = df.groupby("label")["단어수"].mean()

# 3. 두 평균 차이의 절댓값 구하기
diff = abs(m["spam"] - m["ham"])

# 4. 소수 셋째 자리까지 반올림
print(round(diff, 3))

# 정답: 0.047

0.047

In [ ]:
# 풀이2
import pandas as pd
# 데이터 불러오기
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bae-v3/main/part4/ch10/hamspam.csv")


# 1. 각 메시지의 단어 개수 구하기 (띄어쓰기 기준)
df["단어수"] = df["text"].str.count(" ") + 1
df.head()

# 2. 스팸과 정상 메시지의 평균 단어 수 구하기
cond1 = df["label"] == "spam"
cond2 = df["label"] == "ham"
m1 = df[cond1]["단어수"].mean()
m2 = df[cond2]["단어수"].mean()

# 3. 두 평균 차이의 절댓값 구하기
diff = abs(m1 - m2)

# 4. 소수 셋째 자리까지 반올림
print(round(diff, 3))

# 정답: 0.047

0.047