[구글 코랩(Colab)에서 실행하기](https://colab.research.google.com/github/lovedlim/bigdata_analyst_cert_v2/blob/main/part4/ch5/p5_type1.ipynb)

## 작업형1

### 문제1

제공된 데이터셋(df)에서 아래 3가지 조건을 모두 만족하는 데이터만 필터링한 후, '2ℓ가격'의 평균값을 구하시오. 계산된 최종 평균값은 반올림하여 정수 형태로 제출하시오.

종량제봉투종류 컬럼의 값이 '규격봉투'

종량제봉투용도 컬럼의 값이 '음식물쓰레기'

2ℓ가격 컬럼의 값이 0이 아닌 데이터

In [10]:
cond1 = df['종량제봉투종류'] == "규격봉투"
cond2 = df['종량제봉투용도'] == "음식물쓰레기"
cond3 = df['2ℓ가격'] != 0

print(round(df[cond1 & cond2 & cond3]['2ℓ가격'].mean()))

118

In [1]:
import pandas as pd
# df = pd.read_csv("data5-1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch5/data5-1.csv")
df

,시도명,시군구명,종량제봉투종류,종량제봉투처리방식,종량제봉투용도,종량제봉투사용대상,1ℓ가격,1.5ℓ가격,2ℓ가격,2.5ℓ가격,...,60ℓ가격,75ℓ가격,100ℓ가격,120ℓ가격,125ℓ가격,관리부서명,관리부서전화번호,데이터기준일자,제공기관코드,제공기관명
0,경기도,안양시,규격봉투,매립용,생활쓰레기,사업장용,0,0,0,0,...,0,2100,0,0,0,자원순환과,031-8045-5448,2022-08-12,3830000,경기도 안양시
1,경기도,안양시,규격봉투,매립용,생활쓰레기,기타,0,0,0,0,...,0,2100,0,0,0,자원순환과,031-8045-5448,2022-08-12,3830000,경기도 안양시
2,경기도,안양시,규격봉투,소각용,음식물쓰레기,가정용,0,50,0,80,...,0,0,0,0,0,자원순환과,031-8045-5448,2022-08-12,3830000,경기도 안양시
3,경기도,안양시,규격봉투,소각용,음식물쓰레기,사업장용,0,50,0,80,...,0,0,0,0,0,자원순환과,031-8045-5448,2022-08-12,3830000,경기도 안양시
4,경기도,안양시,규격봉투,소각용,음식물쓰레기,기타,0,50,0,80,...,0,0,0,0,0,자원순환과,031-8045-5448,2022-08-12,3830000,경기도 안양시
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
757,충청남도,계룡시,재사용규격봉투,소각용,생활쓰레기,가정용,0,0,0,0,...,0,0,2320,0,0,환경위생과,042-840-2484,2019-05-16,5580000,충청남도 계룡시
758,충청남도,계룡시,재사용규격봉투,소각용,생활쓰레기,사업장용,0,0,0,0,...,0,0,2320,0,0,환경위생과,042-840-2484,2019-05-16,5580000,충청남도 계룡시
759,전라북도,김제시,규격봉투,소각용,생활쓰레기,가정용,0,0,0,0,...,0,0,0,0,0,환경과,063-540-3165,2018-08-09,4710000,전라북도 김제시
760,전라북도,김제시,특수규격마대,매립용,생활쓰레기,가정용,0,0,0,0,...,0,0,0,0,0,환경과,063-540-3165,2018-08-09,4710000,전라북도 김제시
761,전라북도,김제시,김장용봉투,소각용,음식물쓰레기,가정용,0,0,0,0,...,0,0,0,0,0,환경과,063-540-3165,2018-08-09,4710000,전라북도 김제시

In [ ]:
import pandas as pd
# df = pd.read_csv("data5-1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch5/data5-1.csv")

# 1) 조건1.종량제 봉투 종류 ‘규격봉투’
cond1 = df['종량제봉투종류'] == '규격봉투'

# 2) 조건2.종량제 봉투 용도 ‘음식물쓰레기’
cond2 = df['종량제봉투용도'] == '음식물쓰레기'

# 3) 조건3. 2l가격이 0이면 제외
cond3 = df['2ℓ가격'] != 0

# 4) 조건 적용한 데이터
df = df[cond1 & cond2 & cond3]

# 5) 2l 가격 평균 계산, 반올림, 정수 출력
print(round(df['2ℓ가격'].mean()))

118

### 문제2

제공된 데이터셋(df)의 신장(Height, 단위: cm)과 체중(Weight, 단위: kg) 데이터를 활용하여 BMI 파생변수를 계산하시오. 이후 아래 두 조건에 해당하는 인원수(행 수)의 차이를 절대값으로 구하여 정수 형태로 제출하시오.

(단, $\text{BMI} = \text{체중(kg)} / (\text{신장(m)})^2$ 공식을 사용하시오.)조건 1 (정상체중): $\text{BMI} \ge 18.5$ 이면서 $\text{BMI} < 23$조건 2 (위험체중): $\text{BMI} \ge 23$ 이면서 $\text{BMI} < 25$

In [20]:
df['bmi'] =df['Weight'] /(df['Height']/100)**2
df_normal = df[(df['bmi']>= 18.5) & (df['bmi'] < 23)]
df_abnormal = df[(df['bmi']>= 23) & (df['bmi'] < 25)]

print(abs(len(df_normal) - len(df_abnormal)))

144

In [11]:
import pandas as pd
# df = pd.read_csv("data5-2.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch5/data5-2.csv")
df

      Gender  Height  Weight
0       Male   187.6   109.7
1       Male   174.7    73.6
2       Male   188.2    96.5
3       Male   182.2    99.8
4       Male   177.5    93.6
...      ...     ...     ...
9995  Female   168.1    62.0
9996  Female   170.4    77.5
9997  Female   162.2    58.3
9998  Female   175.3    74.3
9999  Female   157.3    51.6

[10000 rows x 3 columns]

In [ ]:
import pandas as pd
# df = pd.read_csv("data5-2.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch5/data5-2.csv")

# 1) bmi 파생변수 계산
df['bmi'] = df['Weight'] / (df['Height']/100)**2

# 2) 조건1. 정상체중 bmi
cond1 = (df['bmi'] >= 18.5) & (df['bmi'] < 23)

# 3) 조건2. 위험체중 bmi
cond2 = (df['bmi'] >= 23) & (df['bmi'] < 25)

# 4) 조건1의 인원와 조건2의 인원 차이계산, 절대값 처리
print(abs(len(df[cond1]) - len(df[cond2])))

144

### 문제3

제공된 데이터셋(df)에서 '전입학생수(계)'에서 '전출학생수(계)'를 뺀 값을 '순전입'이라는 파생변수로 생성하시오. 생성된 '순전입' 값이 가장 큰(가장 높은) 학교(행)를 찾아 해당 학교의 '전체 학생 수'를 정수 형태로 제출하시오.

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6309 entries, 0 to 6308
Data columns (total 31 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   시도교육청       6309 non-null   object
 1   지역교육청       6309 non-null   object
 2   지역          6304 non-null   object
 3   정보공시 학교코드   6309 non-null   object
 4   학교명         6309 non-null   object
 5   학교급코드       6309 non-null   int64
 6   설립구분        6309 non-null   object
 7   제외여부        6309 non-null   object
 8   제외사유        2 non-null      object
 9   1학년 전입학생수   6307 non-null   float64
 10  1학년 전출학생수   6307 non-null   float64
 11  1학년 전체학생수   6307 non-null   float64
 12  2학년 전입학생수   6307 non-null   float64
 13  2학년 전출학생수   6307 non-null   float64
 14  2학년 전체학생수   6307 non-null   float64
 15  3학년 전입학생수   6307 non-null   float64
 16  3학년 전출학생수   6307 non-null   float64
 17  3학년 전체학생수   6307 non-null   float64
 18  4학년 전입학생수   6307 non-null   float64
 19  4학년 전출학생수   6307 non-null   float64
 20  4학년 전체학생수   6307 non-null   float64
 21  5학년 전입학생수   6307 non-null   float64
 22  5학년 전출학생수   6307 non-null   float64
 23  5학년 전체학생수   6307 non-null   float64
 24  6학년 전입학생수   6307 non-null   float64
 25  6학년 전출학생수   6307 non-null   float64
 26  6학년 전체 학생수  6307 non-null   float64
 27  전입학생수(계)    6307 non-null   float64
 28  전출학생수(계)    6307 non-null   float64
 29  전체학생수(계)    6307 non-null   float64
 30  순전입         6307 non-null   float64
dtypes: float64(22), int64(1), object(8)
memory usage: 1.5+ MB

In [32]:
df['순전입'] = df['전입학생수(계)'] - df['전출학생수(계)']
df
print(int(df.iloc[df['순전입'].idxmax()]['전체학생수(계)']))

230

In [21]:
import pandas as pd
# df = pd.read_csv("data5-3.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch5/data5-3.csv")
df

,시도교육청,지역교육청,지역,정보공시 학교코드,학교명,학교급코드,설립구분,제외여부,제외사유,1학년 전입학생수,...,4학년 전체학생수,5학년 전입학생수,5학년 전출학생수,5학년 전체학생수,6학년 전입학생수,6학년 전출학생수,6학년 전체 학생수,전입학생수(계),전출학생수(계),전체학생수(계)
0,서울특별시교육청,교육부,서울특별시 서초구,S000003511,서울교육대학교부설초등학교,2,국립,N,NaN,5.0,...,104.0,0.0,0.0,108.0,0.0,0.0,111.0,6.0,0.0,611.0
1,서울특별시교육청,교육부,서울특별시 종로구,S000003563,서울대학교사범대학부설초등학교,2,국립,N,NaN,4.0,...,104.0,3.0,2.0,104.0,0.0,1.0,106.0,20.0,21.0,621.0
2,서울특별시교육청,서울특별시강남서초교육지원청,서울특별시 강남구,S010000738,서울개일초등학교,2,공립,N,NaN,13.0,...,179.0,19.0,8.0,177.0,16.0,5.0,152.0,118.0,50.0,1004.0
3,서울특별시교육청,서울특별시강남서초교육지원청,서울특별시 강남구,S010000741,서울구룡초등학교,2,공립,N,NaN,2.0,...,129.0,18.0,4.0,129.0,13.0,3.0,119.0,90.0,27.0,733.0
4,서울특별시교육청,서울특별시강남서초교육지원청,서울특별시 강남구,S010000742,서울논현초등학교,2,공립,N,NaN,1.0,...,48.0,2.0,10.0,53.0,0.0,0.0,47.0,6.0,29.0,290.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6304,제주특별자치도교육청,제주시교육지원청,제주특별자치도 제주시,S170000801,월랑초등학교,2,공립,N,NaN,1.0,...,129.0,8.0,4.0,135.0,1.0,4.0,106.0,22.0,26.0,699.0
6305,제주특별자치도교육청,제주시교육지원청,제주특별자치도 제주시,S170000834,이도초등학교,2,공립,N,NaN,2.0,...,192.0,4.0,6.0,218.0,2.0,3.0,174.0,29.0,47.0,1182.0
6306,제주특별자치도교육청,제주시교육지원청,제주특별자치도 제주시,S170000836,도련초등학교,2,공립,N,NaN,2.0,...,200.0,3.0,6.0,183.0,1.0,6.0,150.0,22.0,51.0,1170.0
6307,제주특별자치도교육청,제주시교육지원청,제주특별자치도 제주시,S170000837,삼화초등학교,2,공립,N,NaN,6.0,...,145.0,6.0,6.0,128.0,3.0,6.0,158.0,31.0,42.0,795.0
6308,제주특별자치도교육청,제주시교육지원청,제주특별자치도 제주시,S170000839,하귀일초등학교,2,공립,N,NaN,13.0,...,95.0,9.0,13.0,103.0,8.0,17.0,108.0,79.0,76.0,624.0

In [ ]:
import pandas as pd
# df = pd.read_csv("data5-3.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch5/data5-3.csv")

# 1) '순전입' 파생변수 계산
df['순전입'] = df['전입학생수(계)'] - df['전출학생수(계)']

# 2) '순전입' 컬럼 기준으로 내림차순 정렬
df = df.sort_values('순전입', ascending=False)

# 3) 첫번째 행의 전체 학생 수 값 선택
print(int(df.iloc[0,-2]))

230