[구글 코랩(Colab)에서 실행하기](https://colab.research.google.com/github/lovedlim/bigdata_analyst_cert_v2/blob/main/part4/ch7/p7_type1.ipynb)

## 작업형1

### 문제1

In [18]:
ass = df['id_assessment'].value_counts().idxmax()
df1 = df[df['id_assessment'] == ass]

#print(df1.head())
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
#print(help(scaler))
df1['score'] = scaler.fit_transform(df1[['score']])
#df1['score'] = scaler.fit_transfrom(df1['score'])

df1['score'].max()
#print(df1.head())

/tmp/ipykernel_13692/988045316.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['score'] = scaler.fit_transform(df1[['score']])

2.183422032552496

In [3]:
df = df.dropna()
df.isnull().sum()

id_assessment        0
student_id           0
study_period_days    0
score                0
dtype: int64

In [1]:
import pandas as pd
# df = pd.read_csv("student_assessment.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch7/student_assessment.csv")
df

      id_assessment  student_id  study_period_days  score
0               103           0                 22   87.0
1                93           1                 70   92.0
2                15           2                 22    2.0
3               107           3                 22   51.0
4                72           4                 22   73.0
...             ...         ...                ...    ...
2560             96        2695                 35    3.0
2561             38        2696                 22   77.0
2562             87        2697                 22   88.0
2563             88        2698                 70   67.0
2564             50        2699                 22   24.0

[2565 rows x 4 columns]

In [ ]:
import pandas as pd
# df = pd.read_csv("student_assessment.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch7/student_assessment.csv")

# 1) 결측치 제거
# print(df.shape)
df = df.dropna()
# print(df.shape)

# 2) 가장 많이 수강한 과목 필터링
id = df['id_assessment'].value_counts().idxmax()
cond = df['id_assessment'] == id
df = df[cond]

# 3) 과목 점수 스탠다드 스케일
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df['score'] = scaler.fit_transform(df[['score']])

# 4) 가장 큰 값
print(round(df['score'].max(), 3))

2.183

### 문제2

In [ ]:
import pandas as pd
# df = pd.read_csv("stock_market.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch7/stock_market.csv")

# 1) close와의 상관관계(절대값)
df_corr = df.corr()['close'].abs()

# 2) 상관관계가 높은 변수명
col = df_corr.loc['DE1':'DE77'].idxmax()

# 3) '2)'에서 구한 변수명의 평균값
print(round(df[col].mean(), 4))

-0.0004

### 문제3

In [ ]:
import pandas as pd
# df = pd.read_csv("air_quality.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch7/air_quality.csv")

# 1) IQR 계산
Q1 = df['CO2'].quantile(0.25)
Q3 = df['CO2'].quantile(0.75)
IQR = Q3 - Q1

# 2) 상한 및 하한 계산
upper = Q3 + 1.5 * IQR
lower = Q1 - 1.5 * IQR

# 3) 이상치 식별
outliers = df[(df['CO2'] < lower) | (df['CO2'] > upper)]

# 4) 이상치 수
print(len(outliers))

304