[구글 코랩(Colab)에서 실행하기](https://colab.research.google.com/github/lovedlim/bigdata_analyst_cert_v2/blob/main/part4/ch7/p7_type1.ipynb)

## 작업형1

### 문제1

제공된 데이터셋(df)에서 결측치(NaN)가 포함된 행을 모두 제거하시오. 결측치가 제거된 데이터 중 가장 많이 등장한(가장 많이 수강한) id_assessment 값을 찾아 해당 과목의 데이터만 필터링하시오. 필터링된 데이터의 score(점수) 컬럼에 대해 표준화(StandardScaler)를 수행하고, 변환된 score 값 중 최대값을 구하여 소수점 셋째 자리까지 반올림한 실수 형태로 제출하시오.

In [4]:
df.isnull().sum()
df.shape

(2565, 4)

In [14]:
df = df.dropna()
max_id_assessment = df['id_assessment'].value_counts().idxmax()
df2 = df[df['id_assessment'] == max_id_assessment]
df2.head()

     id_assessment  student_id  study_period_days  score
80              12          85                 35   50.0
131             12         141                 70   32.0
342             12         365                 22   99.0
349             12         372                 22   49.0
368             12         394                 22   33.0

In [23]:
from sklearn.preprocessing import StandardScaler
#print(help(StandardScaler))
scaler = StandardScaler()
df2['score'] = scaler.fit_transform(df2[['score']])
df2['score'].max()
print(round(df2['score'].max(),3))

2.183

/tmp/ipykernel_4038/1494468220.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['score'] = scaler.fit_transform(df2[['score']])

In [1]:
import pandas as pd
# df = pd.read_csv("student_assessment.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch7/student_assessment.csv")
df

      id_assessment  student_id  study_period_days  score
0               103           0                 22   87.0
1                93           1                 70   92.0
2                15           2                 22    2.0
3               107           3                 22   51.0
4                72           4                 22   73.0
...             ...         ...                ...    ...
2560             96        2695                 35    3.0
2561             38        2696                 22   77.0
2562             87        2697                 22   88.0
2563             88        2698                 70   67.0
2564             50        2699                 22   24.0

[2565 rows x 4 columns]

In [ ]:
import pandas as pd
# df = pd.read_csv("student_assessment.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch7/student_assessment.csv")

# 1) 결측치 제거
# print(df.shape)
df = df.dropna()
# print(df.shape)

# 2) 가장 많이 수강한 과목 필터링
id = df['id_assessment'].value_counts().idxmax()
cond = df['id_assessment'] == id
df = df[cond]

# 3) 과목 점수 스탠다드 스케일
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df['score'] = scaler.fit_transform(df[['score']])

# 4) 가장 큰 값
print(round(df['score'].max(), 3))

2.183

### 문제2

제공된 데이터셋(df)에서 close(종가) 변수와 다른 모든 수치형 변수 간의 피어슨 상관계수의 절대값을 구하시오. 이 중 DE1부터 DE77까지의 변수 범위 내에서 close 변수와의 상관계수 절대값이 가장 큰(가장 높은) 변수명을 찾으시오. 최종적으로 해당 변수의 전체 평균값을 구하여 소수점 넷째 자리까지 반올림한 실수 형태로 제출하시오.

In [43]:
idx = df.corr()['close'][:77].abs().idxmax()
result = df.loc[:,idx].mean()
print(round(result,4))

-0.0004

In [24]:
import pandas as pd
# df = pd.read_csv("stock_market.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch7/stock_market.csv")
df

,DE1,DE2,DE3,DE4,DE5,DE6,DE7,DE8,DE9,DE10,...,DE71,DE72,DE73,DE74,DE75,DE76,DE77,open,close,volume
0,1.764052,0.400157,0.978738,2.240893,1.867558,-0.977278,0.950088,-0.151357,-0.103219,0.410599,...,0.729091,0.128983,1.139401,-1.234826,0.402342,-0.684810,-0.870797,129.549102,126.502056,981466.0
1,-0.578850,-0.311553,0.056165,-1.165150,0.900826,0.465662,-1.536244,1.488252,1.895889,1.178780,...,1.117016,-1.315907,-0.461585,-0.068242,1.713343,-0.744755,-0.826439,126.502056,128.041811,473416.0
2,-0.098453,-0.663478,1.126636,-1.079932,-1.147469,-0.437820,-0.498032,1.929532,0.949421,0.087551,...,-1.540797,0.063262,0.156507,0.232181,-0.597316,-0.237922,-1.424061,128.041811,128.957651,46597.0
3,-0.493320,-0.542861,0.416050,-1.156182,0.781198,1.494485,-2.069985,0.426259,0.676908,-0.637437,...,1.658131,-0.118164,-0.680178,0.666383,-0.460720,-1.334258,-1.346718,128.957651,122.965246,455747.0
4,0.693773,-0.159573,-0.133702,1.077744,-1.126826,-0.730678,-0.384880,0.094352,-0.042171,-0.286887,...,-0.206904,0.880179,-1.698106,0.387280,-2.255564,-1.022507,0.038631,122.965246,114.922790,242198.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1.020937,-0.942656,-0.437589,0.400197,0.280305,-0.239677,-0.523317,-0.070756,0.813117,-0.394868,...,-0.658888,0.129819,0.343603,0.240547,0.869118,-0.200800,-2.477692,50.254255,31.155158,955899.0
996,0.116310,-0.387522,-0.135163,0.427945,0.020041,-1.281488,-0.003546,0.517104,-0.798964,-0.590362,...,-0.297669,0.652641,0.807874,-2.239079,-1.378841,-0.020303,1.058002,31.155158,35.253943,646770.0
997,-0.167591,-0.304002,0.407705,1.625603,-0.480631,1.546496,-0.288261,-0.625352,1.186237,0.270277,...,0.200219,0.242471,2.453099,0.111067,-1.904594,0.643397,0.416017,35.253943,44.833041,887211.0
998,-1.780806,-0.133918,0.825544,-0.223826,0.426823,1.024924,0.847111,1.370670,1.187785,-0.938389,...,0.946004,-0.418479,-1.790980,-1.013184,-0.316554,-2.145770,-0.987003,44.833041,56.070234,174999.0
999,-0.917195,-0.191702,-0.795384,0.676718,-0.321088,1.302167,-0.407516,1.520332,0.355029,-1.480904,...,-0.229409,-0.014024,1.347451,0.966457,-0.553087,0.502263,-0.417586,56.070234,56.017586,640705.0

In [42]:
import pandas as pd
# df = pd.read_csv("stock_market.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch7/stock_market.csv")

# 1) close와의 상관관계(절대값)
df_corr = df.corr()['close'].abs()

# 2) 상관관계가 높은 변수명
col = df_corr.loc['DE1':'DE77'].idxmax()
print(col)

# 3) '2)'에서 구한 변수명의 평균값
print(round(df[col].mean(), 4))

DE14
-0.0004

### 문제3

제공된 데이터셋(df)의 CO2 컬럼을 대상으로 IQR(사분위간 범위) 방식에 기반한 이상치 검출을 수행하고자 한다. 아래의 이상치 판단 기준(상한값 초과 또는 하한값 미만)을 적용했을 때, 이상치에 해당하는 데이터(행)의 총 개수를 정수 형태로 제출하시오.

$\text{IQR} = \text{제3사분위수(Q3)} - \text{제1사분위수(Q1)}$$\text{상한선(Upper Boundary)} = \text{Q3} + 1.5 \times \text{IQR}$$\text{하한선(Lower Boundary)} = \text{Q1} - 1.5 \times \text{IQR}$

In [51]:
Q1 = df['CO2'].quantile(0.25)
Q3 = df['CO2'].quantile(0.75)
IQR = Q3- Q1
print(Q1, Q3, IQR)
upper = Q3 + 1.5*IQR
lower = Q1 - 1.5*IQR
print(len(df[(df['CO2']> upper) | (df['CO2'] < lower)]))

383.8502072254157 418.7784333384595 34.92822611304376
304

In [44]:
import pandas as pd
# df = pd.read_csv("air_quality.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch7/air_quality.csv")
df

                     Date        CO         CO2         O2
0     2024-01-01 00:00:00  0.549671  383.037632  21.248286
1     2024-01-01 01:00:00  0.486174  392.362513  21.183324
2     2024-01-01 02:00:00  0.564769  385.065473  19.963480
3     2024-01-01 03:00:00  0.652303  402.760451  21.479584
4     2024-01-01 04:00:00  0.476585  429.929463  19.409917
...                   ...       ...         ...        ...
9995  2025-02-20 11:00:00  0.630110  409.695684  20.322712
9996  2025-02-20 12:00:00  0.300166  434.434164  22.344604
9997  2025-02-20 13:00:00  0.429468  409.458849  20.398633
9998  2025-02-20 14:00:00  0.549577  442.838243  19.007643
9999  2025-02-20 15:00:00  0.564439  359.502005  20.671116

[10000 rows x 4 columns]

In [ ]:
import pandas as pd
# df = pd.read_csv("air_quality.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch7/air_quality.csv")

# 1) IQR 계산
Q1 = df['CO2'].quantile(0.25)
Q3 = df['CO2'].quantile(0.75)
IQR = Q3 - Q1

# 2) 상한 및 하한 계산
upper = Q3 + 1.5 * IQR
lower = Q1 - 1.5 * IQR

# 3) 이상치 식별
outliers = df[(df['CO2'] < lower) | (df['CO2'] > upper)]

# 4) 이상치 수
print(len(outliers))

304